import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import NProgressProvider from "./nprogress-provider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Yeti Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased dark scroll-smooth`}
    >
      <body
        className="font-[family-name:var(--font-geist-mono)]
        text-white
      "
      >
        <NProgressProvider />
        <Navigation />
        <div className="relative">
          <main className="px-6 pb-8">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
